# Generated by Django 2.2 on 2020-12-01 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_on_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='on_sale',
        ),
    ]
