# Generated by Django 2.2 on 2020-12-02 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20201202_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacity',
            name='code',
        ),
    ]
