# Generated by Django 2.2 on 2020-12-09 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogImage',
        ),
    ]
