# Generated by Django 2.2 on 2020-11-15 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactmessage_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='phone',
        ),
    ]
